### ISSUE TITLE
App wouldn't install

### ISSUE THREAD

**Issue by kl3eo** [NilabhB/SkyMeet#6]
After I built the app with Android Studio, jdk-11 or jdk1.8, or gradle 6, or gradle 7, then I signed apk with jarsigner; then I tried to install it on Android 9 and then on Android 5 device - it wouldn't install. Error is in the process of install, saying apk file is corrupt. I can build other apps and sign and install, and run them, but both Jitsi Android SDK example app, and Skymeet app wouldn't install. What can the problem be?

**Comment by NilabhB** [comment]
I am not exactly sure what's causing the issue, but SkyMeet won't install in Android 5 as I have set it min. Android 6. However if you try to install from playstore, you shouldn't face any issue. If you are trying to built your own conferencing app using Jitsi Android SDK, I can help you in that.

**Comment by NilabhB** [comment]
Closing the case as I didn't hear back.
